#version: "3.8"

services:
  rabbitmq:
    image: dygood/rabbitmq-dlx:latest
    hostname: rabbitserver
    environment:
      - TZ=Asia/Chongqing
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=a123456
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      resources:
        limits:
          memory: 1G
